import { rubik } from "@/core/assets/style/fonts/font";
import type { Metadata } from "next";
import NextTopLoader from "nextjs-toploader";
import { Toaster } from "sonner";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${rubik.variable} ${rubik.variable} antialiased`}>
        <NextTopLoader color="#dd5c34" />
        <Toaster />
        {children}
      </body>
    </html>
  );
}
