
FROM oven/bun:1.3.9 AS base

WORKDIR /app

RUN bun add -g turbo

# -------------------------

FROM base AS pruner

COPY . .

RUN turbo prune web --docker

# -------------------------

FROM oven/bun:1.3.9 AS installer

WORKDIR /app

COPY --from=pruner /app/out/json/ .

RUN bun install --frozen-lockfile

COPY --from=pruner /app/out/full/ .

RUN bun run --filter web build

# -------------------------

FROM oven/bun:1.3.9 AS runner

WORKDIR /app

ENV NODE_ENV=production


COPY --from=installer /app/apps/web/.next/standalone ./
COPY --from=installer /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer /app/apps/web/public ./apps/web/public


EXPOSE 3000

CMD ["bun",  "apps/web/server.js"]
