FROM node:22-alpine AS base

WORKDIR /app

RUN corepack enable && corepack prepare pnpm@11.25.0 --activate
RUN pnpm add -g turbo

# -------------------------

FROM base AS pruner

COPY . .

RUN turbo prune web --docker

# -------------------------

FROM base AS installer

WORKDIR /app

COPY --from=pruner /app/out/json/ .

RUN pnpm install --frozen-lockfile

COPY --from=pruner /app/out/full/ .

RUN pnpm run --filter web build

# -------------------------

FROM node:22-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=installer /app/apps/web/.next/standalone ./
COPY --from=installer /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer /app/apps/web/public ./apps/web/public

EXPOSE 3000

CMD ["node", "apps/web/server.js"]
