FROM oven/pnpm:1.3.9 AS base

WORKDIR /app

RUN pnpm add -g turbo

# -------------------------

FROM base AS pruner

COPY . .

RUN turbo prune api --docker

# -------------------------

FROM oven/pnpm:1.3.9 AS installer

WORKDIR /app

COPY --from=pruner /app/out/json/ .

RUN pnpm install --frozen-lockfile

COPY --from=pruner /app/out/full/ .

RUN pnpm run --filter api build

# -------------------------

FROM oven/pnpm:1.3.9 AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=installer /app .

WORKDIR /app/apps/api

EXPOSE 3001

CMD ["pnpm","run","start:prod"]
