
FROM oven/pnpm:1.3.9 AS base

WORKDIR /app

RUN pnpm add -g turbo

# -------------------------

FROM base AS pruner

COPY . .

RUN turbo prune web --docker

# -------------------------

FROM oven/pnpm:1.3.9 AS installer

WORKDIR /app

COPY --from=pruner /app/out/json/ .

RUN pnpm install --frozen-lockfile

COPY --from=pruner /app/out/full/ .

RUN pnpm run --filter web build

# -------------------------

FROM oven/pnpm:1.3.9 AS runner

WORKDIR /app

ENV NODE_ENV=production


COPY --from=installer /app/apps/web/.next/standalone ./
COPY --from=installer /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=installer /app/apps/web/public ./apps/web/public


EXPOSE 3000

CMD ["pnpm",  "apps/web/server.js"]
